### ISSUE TITLE
Please consider uploading sdist (or Py3.10 wheel) to PyPI

### ISSUE THREAD

**Issue by anntzer** [ToruNiina/libasd#8]
PyPI currently has neither Python 3.10 wheels nor sdists; therefore Py3.10 users need to install libasd directly from the git repo.  Uploading a wheel would be helpful, but that's more work for you (especially as you'd have to redo this every year with every new Python release); uploading a sdist would fix this once and for all (at least for users who have a compiler toolchain installed).
Thanks!

**Comment by ToruNiina** [comment]
Thank you, I didn't know about `sdist`.

Since I didn't know about `sdist`, I totally don't have any idea about how to package and upload an `sdist` file. So I guess it takes long time to have done it. Because I currently have several other tasks, and also there is already a workaround to install this, (I mean building it manually, ) the priority of this repository is currently low.

A pull request, or detailed information about how to package a repository that is written in C++/pybind11 as an `sdist` file is very welcome.

For the time being, I will manually run CI and upload wheel.
I have just released a patch version for python 3.10.

**Comment by anntzer** [comment]
Thanks for the quick upload.  I'll open a PR separately for sdist support.
